export const BULK_TEMPLATE_HEADERS = [
  "nama_pengirim",
  "telepon_pengirim",
  "alamat_pengirim",
  "nama_penerima",
  "telepon_penerima",
  "alamat_penerima",
  "lokasi_tujuan",
  "isi_paket",
  "berat_gram",
  "jumlah_paket",
  "panjang_cm",
  "lebar_cm",
  "tinggi_cm",
  "nilai_barang",
  "metode_pembayaran",
] as const;
